### ISSUE TITLE
Frequent Disconnects

### ISSUE THREAD

**Issue by mikecreates86** [bitfocus/companion-module-tplink-kasasmartplug#1]
First of all, this is a lifesaver plugin because I was controlling my plugs via IFTTT until I just saw they are charging for that service now. Plus that traveled over the web and this is all local network so it's great overall.

However, on the latest build I'm finding that the instances disconnect frequently. I have six separate instances controlling six plugs and they all do it. Seems that especially after an on or off is triggered they go dead for a few seconds. Problem this causes is that that my Stream Deck ON and OFF buttons that control all 6 of these end up being sporadic. Sometimes they turn on all six. Other times just 2 or 3 because the remaining 2 or 3 are disconnected at the moment. Seems to just cycle disconnects as I watch my instances.

Any help or ideas here?

**Comment by mikecreates86** [comment]
Ok after taking a video, it's happening at almost exactly 1 minute intervals. Not sure if that helps.

**Comment by josephdadams** [comment]
Thanks! Glad you like it.

In my experience, that's just what these devices do if you send them the payload. They turn on (or off) and then disconnect you.

I could rewrite the module so that it only opens a TCP connection long enough to send the payload, and then disconnect (or allow a disconnect). If you have a development environment, I can send you something to test on, or, you can wait until it's updated in the core at some point.

**Comment by josephdadams** [comment]
@mikecreates86 PR #2 should solve this issue for you. Test it out and let me know what you think.

**Comment by mikecreates86** [comment]
So to be clear, if I update companion to the lates build I'll be able to test this for you? And with the new code, will it still be a 1 minute delay every time before the plugs will take another command? Not really an issue I guess but just curious.

**Comment by josephdadams** [comment]
No, it is not in the latest build, but you can set up a development environment for yourself and test it out. If it works, I'll merge it into the master branch of this module and then we can look into getting it included into the latest beta builds.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion/wiki/Module-Development

**Comment by mikecreates86** [comment]
Yeah unfortunately I'm not really familiar with all of this as much as I think I need to be to do that.

**Comment by mikecreates86** [comment]
I'm currently running everything on Companion Pi.

**Comment by josephdadams** [comment]
* `cd` to the Companion folder.
* `cd lib`
* `cd module`
* `rm -r tplink-kasasmartplug`
* `git clone -b tcp-rewrite --single-branch https://github.com/bitfocus/companion-module-tplink-kasasmartplug.git`
* `mv companion-module-tplink-kasasmartplug tplink-kasasmartplug`

**Comment by mikecreates86** [comment]
Ok let me try

**Comment by mikecreates86** [comment]
Ok currently stuck trying to cd to the Companion folder...sorry I don't know much about how Companion Pi is setup

**Comment by josephdadams** [comment]
Any luck?

**Comment by mikecreates86** [comment]
Never figured out how to install it on Companion Pi remotely.

————
Mike Moore

**Comment by MichaelAllen** [comment]
I just tested and can confirm that PR #2 fixes the disconnect issue for me. 👍

**Comment by mikecreates86** [comment]
What is PR #2?

**Comment by MichaelAllen** [comment]
@mikecreates86 That was the fix Joseph mentioned testing above. Now that it has been tested, the next step is for it to be merged so it can be included in a build. After that happens, you would be able to download a new version of Companion with the fix included.

**Comment by josephdadams** [comment]
I'll merge it now that you've tested it. :)

**Comment by josephdadams** [comment]
It's in the latest beta builds now.
