### ISSUE TITLE
Bug in latest module

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-module-tplink-kasasmartplug#10]
I just picked up the HS300. Using 1.1.0.
`instance(plug-vc): Error checking feedback: Cannot read property 'state' of undefined`
Feedback works OK. The actions (on/off/toggle) do NOT work

**Comment by josephdadams** [comment]
Do you get the error when trying to run the action?

**Comment by istnv** [comment]
Power On and Power Off sometimes work.
Power Toggle gives the error.

**Comment by josephdadams** [comment]
I pushed a fix for this in the feedbacks, let me know if it still persists.

**Comment by istnv** [comment]
looks good, thanks!
