### ISSUE TITLE
TP Link updated the KASA line, it is now called TAPO

### ISSUE THREAD

**Issue by MaierMatthias** [bitfocus/companion-module-tplink-kasasmartplug#11]
On amazon the "kasa" product line for power sockets is not available anymore. The power sockets from TP Link are now called "TP Link tapo P100". It seems like they refreshed hard- and software for their new product line.

Sadly, the initial implementation for the KASA line is not working with the new TAPO line.

https://www.amazon.com/TP-Link-Tapo-Required-Appliances-P100/dp/B07ZQYVXH8/

PS: Thanks for the great work and the initial implementation!

**Comment by MaierMatthias** [comment]
Seems like the guys from home-assistant.io got it running - see their thread here: https://community.home-assistant.io/t/tp-link-tapo-p100/147792/271

**Comment by josephdadams** [comment]
Just use the Tapo module I made 😃

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-tplink-taposmartplug

**Comment by MaierMatthias** [comment]
Ow wow that's great news! Thank you so much @josephdadams !

It's not showing up in my instance of Bitfocus Companion, do I have to add it manually?

**Comment by josephdadams** [comment]
You just need to update Companion to the latest version

**Comment by MaierMatthias** [comment]
Downloaded the newest version from their website today (v2.2.0) - only the "older" module for KASA is showing up (see attached screenshot
![bitfocus](https://user-images.githubusercontent.com/28765379/163062703-02503017-99be-4e44-8563-eacbbb29baad.png)
)
