### ISSUE TITLE
Connections Status not updating

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-tplink-kasasmartplug#12]
Nice work.

Just found out that Connections Status will not update automatically upon device availability.
<img width="894" alt="Screen Shot 2022-04-28 at 11 15 48 am" src="https://user-images.githubusercontent.com/104544409/165670574-6ec0871f-f2ed-45cf-9735-469bfff7fe31.png">

**Reproduce:** 
1. Restart companion while the Smart Plug is removed from the wall socket.
2. Connections status says "connecting".
3. Plug the Smart Plug back in and confirm the plug is online in Kasa App.
4. Connections status stays "connecting" but plug can be controlled via companion but feedback messages are not working.

All my other modules will automatically go into OK status upon network availability (when the device is up).

But if you edit and Save the connection it will become "OK" in status and feedback starts working.

**Comment by tpk001** [comment]
@josephdadams 
I think this is recently implemented in the module for tapo plugs.

**Comment by josephdadams** [comment]
I will see what I can do about this.

**Comment by brhanna1** [comment]
Any fix on this? I cannot get mine to connect at all. Never goes to "error" on the instance, just continually showing "connecting..." I tried making a button to see if I could still control but there is no response from the plug.

**Comment by josephdadams** [comment]
The status gets updated to "Ok" when the getInformation function is called. My guess is that unless polling is enabled, that function does not get called.
