### ISSUE TITLE
v3 compatibility and static IP

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-tplink-kasasmartplug#14]
Two quick questions - 

I notice the orange alert symbol for the tplink Kasa Smart plug module is present in Companion v3rc1 – is this module fully supported in v3? 

Secondly, there are times on rebooting my studio my router reassigns the devices IP address. The Kasa app still identifies the correct plug, but Companion can lose track of it if the IP doesn't match what is saved in the module settings. I can't see anywhere to set a static IP in the Kasa app... just wondering if you have any suggestions to lock the IP for each plug?

**Comment by davidjoshuaford** [comment]
Thanks Joseph

**Comment by josephdadams** [comment]
I've pushed this into the beta builds. It was working fine for what I needed it to do.

**Comment by davidjoshuaford** [comment]
Thanks!

**Comment by scotttroyer** [comment]
I see that this issue is closed. When will this be pushed to stable?
