### ISSUE TITLE
Memory Leak? in 3.0 builds

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-tplink-kasasmartplug#15]
I have been chasing down a performance issue in the latest 3.0 builds that I thought was related to vMix.  I have noticed that all 6 of my Kasa instances have been going offline after an amount of time.  At the same time my memory use is 80%+ (16GB).  When I kill the TPLINK instances the memory drops off to normal (~40%) and performance increases.  I finally caught this error today.  Any ideas?  Thanks!
![tplink error](https://github.com/bitfocus/companion-module-tplink-kasasmartplug/assets/51127807/e4a57fb2-7233-410c-9194-3b361ada1121)

**Comment by Julusian** [comment]
Yeah.. for every poll it was adding new event listeners to each plug, as well as starting some more polling..
I think this is fixed in the next module sync, but I am not 100% certain

**Comment by obcocav** [comment]
@Julusian. Great!  I don’t see a version update so anyway to know when/if it’s in the betas to confirm the fix?  Thanks!

**Comment by Julusian** [comment]
The fix is in beta 6009 and later

**Comment by obcocav** [comment]
So it does look like that issue is solved!  But I have 2 KP200 switches and on HS103 plug at continues to show a connection error after some time where they never did before.  Just opened the log and restarted the connections so hope to catch something there when it happens later today.  No rhyme or reason so far it appears they just time out.  If I open the connection settings, change nothing, and save to close they connect instantly.  Same if I disconnect and reconnect.  All is then well for a while.  The 4 or so plugs aren't having these disconnects.  Thanks!

**Comment by obcocav** [comment]
Looks to be resolved in 6021+.
