### ISSUE TITLE
Connection state will not auto recover

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-tplink-kasasmartplug#24]
Excellent work.

On issue identified recently (Tested on 2.1.3).
If a plug is removed and the connection goes to an error state. This is expected but when you put the plug back in, the connection state report "error" even though it started working.

Reproduce:

    Restart companion while the Smart Plug is removed from the wall socket.
    Connections status says "error...".
    Plug the Smart Plug back in and confirm the plug is online in Kasa App.
    Connections status stays "error..." but plug can be controlled via companion and feedback messages are working.

@istnv @josephdadams

**Comment by istnv** [comment]
pr #25
