### ISSUE TITLE
Connection state: ERROR even though variables can still be changed

### ISSUE THREAD

**Issue by orrinwitt** [bitfocus/companion-module-tplink-kasasmartplug#27]
The title may not be the best way to describe it, but here's the gist:
I have 4 Kasa smart plugs that will almost always be in ERROR state in companion after a day or so. When using a trigger that is set up to turn everything on, they will not work in this state. But if I manually trigger a power state change via button press, they will turn on and off as expected, but the feedback in companion won't change, and the ERROR state remains. 

If I disable and reenable the conection or make any change and click save, everything will be right again, but obviously I shouldn't have to do that.

I assumed the polling setting was the problem, but polling toggle is on. To be honest, I think this is where the problem is, because it does not seem to be polling when the ERROR state persists. 

Also, the logs seem to show nothing, although I may not be accessing them correctly.

**Comment by istnv** [comment]
This has been fixed in the beta release.

**Comment by orrinwitt** [comment]
> This has been fixed in the beta release.

Awesome! I'll give that a try. Thanks!
