### ISSUE TITLE
Can't connect to TP-Link EP25

### ISSUE THREAD

**Issue by samcosborn** [bitfocus/companion-module-tplink-kasasmartplug#29]
I can't seem to connect to the tp-link kasa ep25 with companion. I can easily ping the ip address with no packet loss. I have tried multiple plugs and multiple ip addresses and multiple machines. Any idea as to why I wouldn't be able to connect to the ep25?

**Comment by istnv** [comment]
That model was not tested (I do not have one :)

**Comment by MrHoaf** [comment]
I have several EP25's that work great, however they are HW Version 1.0.  I recently purchased more and they are Version 2.6, and were not working with my (OLD) version of Companion.  Just updated to current and it is still not working.  Is there a list of tested/supported units?  I'd like to stick with TP-Link/Kasa so I don't need multiple apps...

**Comment by istnv** [comment]
Without the device it is difficult to diagnose. 
I have several EP10 units and a couple of HS300 strips that are rock solid.

**Comment by istnv** [comment]
Looking into this, the EP25 and some newer models require authentication before the device will interact.
The current library does not yet support this.
