### ISSUE TITLE
Please make the polling a configuration option instead of always being on

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-tplink-kasasmartplug#30]
I understand that polling is needed if you want a bad connection or a failed connection to automatically go back to a good connection when it is able to communicate again, but I would like this to be an option that I can choose to enable or not enable. Rarely are my plugs in this state, so constantly polling my four plugs is just wasting resources. If they do get into this state, a simple stop and start of the connection fixes the issue.  I am okay if the default is to enable polling, but I would like it to be an option to disable it.

An example of this is in https://github.com/bitfocus/companion-module-tplink-kasasmartbulb which has an updateInterval config option in milliseconds for the polling time and if set to 0 it disables the polling.

**Comment by istnv** [comment]
Disabling polling also disables any feedbacks and dynamic variables. 
You can turn the plug off manually and button state will follow.
There are also setups where the operator does not have access to the module restart.
Unless you are running a 10Mb network the polling has no significant impact on network traffic.

**Comment by digitaldrummerj** [comment]
@istnv I understand that I don't get feedback or dynamic variables but I don't use nor need either of those for my plugs which is why I prefer not to spend resources on polling that I don't need.  Even though it is a small amount of resources, if every module took a small amount of resources that aren't needed, it quickly adds up to a big amount of resources being used.

I also understand that some setups need polling which is why I suggested to make it an on by default option to keep your new behavior while also having the option to disable the polling like the previous behavior.  I am happy to make the coding changes as long as you approve the direction.

**Comment by istnv** [comment]
It is not a simple matter of turning polling off. This module works on both single plugs and multi-plug strips, but the internal commands to switch the plug on and off are different for each mode. This is determined when the plug responds to the polling. So there would also need to be a configuration for the plug type.
