### ISSUE TITLE
Feature Request: Toggle

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-tplink-kasasmartplug#7]
Heyo,

Any chance to add "Toggle" to this?

I am trying to switch a Kasa plug through companions triggers, but this would require toggle and not on/off as seperate actions

**Comment by josephdadams** [comment]
Yes, I can add this. There's a pending PR that I have to review first but I am also in the process of rewriting this module to follow the kasa smart bulb module I will be posting later this week. The plan is to add a toggle.

**Comment by josephdadams** [comment]
This will be available in the latest version that I will be merging shortly.

**Comment by DachsbauTV** [comment]
Amazing thanks!
