### ISSUE TITLE
Support Kasa LED Light strips

### ISSUE THREAD

**Issue by sleman** [bitfocus/companion-module-tplink-kasasmartplug#8]
Can turn on/off, change colors of KL400 and KL430. Can set custom RGB Colors.

https://www.kasasmart.com/us/products/smart-lighting

reference implementation here: 
https://github.com/python-kasa/python-kasa

**Comment by josephdadams** [comment]
The Kasa light strips module is currently being developed. Have you tried using the kasa smart bulb module with the light strips yet? Just curious.

**Comment by josephdadams** [comment]
I had someone else confirm that the light strips aren't controllable with the bulb module.

**Comment by rrfarmer** [comment]
What's the status on this? How could I contribute, if possible?

**Comment by josephdadams** [comment]
@rrfarmer get excited: https://github.com/bitfocus/companion-module-tplink-kasasmartstrip

**Comment by rrfarmer** [comment]
> @rrfarmer get excited: https://github.com/bitfocus/companion-module-tplink-kasasmartstrip

Thank you sir!!!!
