### ISSUE TITLE
Power State on HS220.

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-tplink-kasasmartplug#9]
Thank so much for your work on this module!  Its awesome!  The new features look great but I havent been able to get feedback on the HS200 switch.  The variables readout but power state remains OFF all the time.  Is this a bug or not supported on that unit?  Thanks!

**Comment by obcocav** [comment]
Never mind

**Comment by obcocav** [comment]
Never mind!  Just saw the option to disable the update with 0 is default!  What is a good number for not overloading things?  thanks!

**Comment by josephdadams** [comment]
I used 2000 on mine (2 seconds) and it seemed ok. On mine, it did seem to take awhile for the outlet to actually turn on after I pressed the button, and same for the feedbacks - but it did work.
